<?php
namespace Tests\Feature;
use App\Models\{Event,Program};use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Http\UploadedFile;use Illuminate\Support\Facades\Storage;use Tests\TestCase;
class CollegeApiTest extends TestCase{use RefreshDatabase;
public function test_content_endpoint_returns_active_programs():void{Program::create(['name'=>'BS Nursing','slug'=>'bs-nursing','duration'=>'4 Years','description'=>'Clinical nursing education','is_active'=>true]);$this->getJson('/api/college-content')->assertOk()->assertJsonPath('data.programs.0.slug','bs-nursing');}
public function test_inquiry_is_validated_and_persisted():void{$payload=['name'=>'Ayesha Khan','email'=>'ayesha@example.com','program'=>'BS Nursing'];$this->postJson('/api/inquiries',$payload)->assertCreated();$this->assertDatabaseHas('inquiries',['email'=>'ayesha@example.com']);}
public function test_invalid_inquiry_returns_validation_errors():void{$this->postJson('/api/inquiries',[])->assertUnprocessable()->assertJsonValidationErrors(['name','email','program']);}
public function test_contact_message_is_validated_and_persisted():void{$payload=['name'=>'Ayesha Khan','email'=>'ayesha@example.com','phone'=>'+92 300 1234567','subject'=>'Admissions guidance','message'=>'Please share the admission requirements.'];$this->postJson('/api/contact-messages',$payload)->assertCreated()->assertJsonPath('message','Your message has been sent successfully.');$this->assertDatabaseHas('contact_messages',['email'=>'ayesha@example.com','subject'=>'Admissions guidance','status'=>'new']);}
public function test_published_event_has_a_dedicated_api_page():void{$event=Event::create(['title'=>'Clinical Awards','slug'=>'clinical-awards','excerpt'=>'Award details','body'=>'The complete award article.','is_published'=>true]);$this->getJson('/api/events/'.$event->slug)->assertOk()->assertJsonPath('data.body','The complete award article.');}
public function test_unpublished_event_is_not_publicly_accessible():void{$event=Event::create(['title'=>'Draft Event','slug'=>'draft-event','excerpt'=>'Draft details','is_published'=>false]);$this->getJson('/api/events/'.$event->slug)->assertNotFound();}
public function test_online_application_is_stored_with_private_documents():void{Storage::fake('local');$program=Program::create(['name'=>'BS Nursing','slug'=>'bs-nursing','duration'=>'4 Years','description'=>'Clinical education','is_active'=>true]);$payload=['program_id'=>$program->id,'first_name'=>'Ayesha','last_name'=>'Khan','date_of_birth'=>'2000-05-10','gender'=>'female','email'=>'ayesha@example.com','phone'=>'+92 300 1234567','address'=>'10 College Road','city'=>'Lahore','country'=>'Pakistan','highest_qualification'=>'FSc Pre-Medical','institution'=>'City College','graduation_year'=>2022,'confirmation'=>true,'transcript'=>UploadedFile::fake()->create('transcript.pdf',100,'application/pdf'),'identity_document'=>UploadedFile::fake()->create('id.pdf',100,'application/pdf')];$this->post('/api/applications',$payload,['Accept'=>'application/json'])->assertCreated()->assertJsonStructure(['data'=>['reference','status']]);$this->assertDatabaseHas('applications',['email'=>'ayesha@example.com','status'=>'submitted']);}
}
