<script setup>
import {computed,onMounted,ref} from 'vue';
import SiteHeader from '../components/SiteHeader.vue';
import SiteFooter from '../components/SiteFooter.vue';
import {getCollegeContent,sendContactMessage} from '../services/api';

const data=ref({site:{}}),form=ref({name:'',email:'',phone:'',subject:'',message:''}),errors=ref({}),busy=ref(false),sent=ref(false);
const value=(key,fallback='')=>data.value.site[key]||fallback;
const phoneLink=(phone)=>`tel:${String(phone).replace(/[^+\d]/g,'')}`;
const whatsAppLink=(phone,message='Hello, I would like information about the college.')=>`https://wa.me/${String(phone).replace(/\D/g,'')}?text=${encodeURIComponent(message)}`;
const whatsapp=computed(()=>value('college_whatsapp',value('college_phone','')));
const departments=computed(()=>[
 {icon:'bi-building',name:'Main Office',detail:'General enquiries',phone:value('college_phone','Contact admissions')},
 {icon:'bi-person-heart',name:'Admissions Department',detail:'Programs and applications',phone:value('admissions_phone',value('college_phone','Contact admissions'))},
 {icon:'bi-headset',name:'Student Support',detail:'Current student assistance',phone:value('support_phone',value('college_phone','Contact admissions'))},
 {icon:'bi-receipt',name:'Accounts & Fees',detail:'Fees and payment enquiries',phone:value('accounts_phone',value('college_phone','Contact admissions'))}
]);
const faqs=computed(()=>[
 [value('contact_faq_1_question','How quickly will you respond?'),value('contact_faq_1_answer','Our team normally responds within two working days.')],
 [value('contact_faq_2_question','Which number should I use for admissions?'),value('contact_faq_2_answer',`Call ${value('admissions_phone',value('college_phone','our main office'))} for program and application guidance.`)],
 [value('contact_faq_3_question','Can I contact you through WhatsApp?'),value('contact_faq_3_answer','Yes. Use the WhatsApp buttons on this page to begin a conversation with our team.')],
 [value('contact_faq_4_question','What are your office hours?'),value('contact_faq_4_answer',value('contact_office_hours','Monday–Friday, 8:30 AM–5:00 PM.'))]
]);
onMounted(async()=>{try{data.value=(await getCollegeContent()).data.data}catch{}document.title=`Contact | ${value('college_name','College of Nursing')}`});
async function submit(){busy.value=true;errors.value={};sent.value=false;try{await sendContactMessage(form.value);sent.value=true;form.value={name:'',email:'',phone:'',subject:'',message:''}}catch(e){errors.value=e.response?.data?.errors||{form:[e.response?.data?.message||'Your message could not be sent.']}}finally{busy.value=false}}
</script>

<template>
 <SiteHeader :site="data.site" active="contact"/>
 <main class="contact-page">
  <section class="contact-conversation"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-6"><span class="contact-kicker">{{value('contact_eyebrow','GET IN TOUCH')}}</span><h1>{{value('contact_title',"Let’s Start a Conversation")}}</h1><p>{{value('contact_description','Get clear guidance from our admissions and student support teams whenever you need it.')}}</p><div class="hero-contact-actions"><a :href="phoneLink(value('college_phone'))" class="btn btn-primary">Call Us</a><a :href="whatsAppLink(whatsapp)" target="_blank" rel="noopener" class="btn btn-outline-dark"><i class="bi bi-whatsapp"></i> Chat on WhatsApp</a></div><div class="contact-promises"><span>Fast response</span><span>Friendly support</span><span>Multiple contact options</span></div></div><div class="col-lg-6"><div class="contact-phone-art"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="phone"><div class="phone-screen"><i class="bi bi-whatsapp"></i></div></div><span class="floating-contact mail"><i class="bi bi-envelope-fill"></i></span><span class="floating-contact pin"><i class="bi bi-geo-alt-fill"></i></span><span class="floating-contact chat"><i class="bi bi-chat-left-text-fill"></i></span></div></div></div>
   <div class="row g-3 contact-quick-grid"><div class="col-sm-6 col-lg-3"><a class="quick-contact-card" :href="phoneLink(value('college_phone'))"><i class="bi bi-telephone-fill"></i><h2>Call Us</h2><b>{{value('college_phone','Contact admissions')}}</b><span>Call Now <i class="bi bi-arrow-up-right"></i></span></a></div><div class="col-sm-6 col-lg-3"><a class="quick-contact-card whatsapp" :href="whatsAppLink(whatsapp)" target="_blank" rel="noopener"><i class="bi bi-whatsapp"></i><h2>WhatsApp</h2><b>{{whatsapp}}</b><span>Start Chat <i class="bi bi-arrow-up-right"></i></span></a></div><div class="col-sm-6 col-lg-3"><a class="quick-contact-card" :href="`mailto:${value('college_email','admissions@example.edu')}`"><i class="bi bi-envelope-fill"></i><h2>Email</h2><b>{{value('college_email','admissions@example.edu')}}</b><span>Send Email <i class="bi bi-arrow-up-right"></i></span></a></div><div class="col-sm-6 col-lg-3"><a class="quick-contact-card" :href="`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(value('college_address'))}`" target="_blank" rel="noopener"><i class="bi bi-geo-alt-fill"></i><h2>Visit Us</h2><b>{{value('college_address','College campus')}}</b><span>Get Directions <i class="bi bi-arrow-up-right"></i></span></a></div></div>
  </div></section>
  <section class="contact-departments"><div class="container"><div class="contact-heading"><span>DIRECT CONTACT</span><h2>Choose the Right Number</h2><p>Connect directly with the team best placed to help.</p></div><div class="row g-3"><div v-for="department in departments" :key="department.name" class="col-md-6"><article class="department-card"><i :class="['bi',department.icon]"></i><div><h3>{{department.name}}</h3><p>{{department.detail}}</p><b>{{department.phone}}</b><a :href="phoneLink(department.phone)" class="btn btn-primary btn-sm">Call {{department.name.replace(' Department','').replace('Main Office','Office')}}</a></div></article></div></div></div></section>
  <section class="contact-whatsapp"><div class="container"><div class="contact-heading text-center"><span>QUICK CONVERSATIONS</span><h2>Chat With Us on WhatsApp</h2><p>Choose the right team for quick, convenient support.</p></div><div class="row g-3 justify-content-center"><div v-for="team in departments.slice(1)" :key="team.name" class="col-md-4"><article class="whatsapp-card"><i class="bi bi-whatsapp"></i><h3>{{team.name}}</h3><b>{{team.phone}}</b><p>{{team.detail}}</p><a :href="whatsAppLink(team.phone,`Hello, I need help from ${team.name}.`)" target="_blank" rel="noopener">Start Chat</a></article></div></div></div></section>
  <section class="contact-message-section"><div class="container"><div class="row g-4"><div class="col-lg-8"><form class="reference-contact-form" @submit.prevent="submit"><span class="contact-kicker">WRITE TO US</span><h2>{{value('contact_form_title','Send Us a Message')}}</h2><p>{{value('contact_form_text','Complete the form and a member of our team will respond shortly.')}}</p><div v-if="sent" class="alert alert-success">Your message was sent successfully. We will be in touch soon.</div><div v-if="errors.form" class="alert alert-danger">{{errors.form[0]}}</div><div class="row g-3"><div class="col-md-6"><label>Full name *</label><input v-model="form.name" class="form-control" :class="{'is-invalid':errors.name}" required><div class="invalid-feedback">{{errors.name?.[0]}}</div></div><div class="col-md-6"><label>Email address *</label><input v-model="form.email" type="email" class="form-control" :class="{'is-invalid':errors.email}" required><div class="invalid-feedback">{{errors.email?.[0]}}</div></div><div class="col-md-6"><label>Phone number</label><input v-model="form.phone" class="form-control"></div><div class="col-md-6"><label>Department / enquiry type *</label><select v-model="form.subject" class="form-select" :class="{'is-invalid':errors.subject}" required><option value="" disabled>Select a department</option><option v-for="x in ['Admissions','Programs and Courses','Fee Structure','Scholarships','Student Support','Campus Visit','General Inquiry']" :key="x">{{x}}</option></select><div class="invalid-feedback">{{errors.subject?.[0]}}</div></div><div class="col-12"><label>Message *</label><textarea v-model="form.message" class="form-control" :class="{'is-invalid':errors.message}" rows="6" required></textarea><div class="invalid-feedback">{{errors.message?.[0]}}</div></div></div><button class="btn btn-primary w-100 mt-3" :disabled="busy"><span v-if="busy" class="spinner-border spinner-border-sm me-2"></span>{{busy?'Sending…':'Send Message'}} <i v-if="!busy" class="bi bi-send"></i></button><small class="secure-note"><i class="bi bi-lock"></i> Your information is sent securely and used only to respond to your enquiry.</small></form></div><div class="col-lg-4"><aside class="direct-panel"><h2>Prefer to Talk Directly?</h2><div><i class="bi bi-telephone"></i><span>Phone<b>{{value('college_phone')}}</b></span></div><div><i class="bi bi-whatsapp"></i><span>WhatsApp<b>{{whatsapp}}</b></span></div><div><i class="bi bi-envelope"></i><span>Email<b>{{value('college_email')}}</b></span></div><div><i class="bi bi-clock"></i><span>Office Hours<b>{{value('contact_office_hours')}}</b></span></div><small><i></i> Open during office hours</small></aside></div></div>
   <div class="contact-facts"><div><i class="bi bi-clock"></i><span>Average Response<b>{{value('contact_response_time','Under 2 working days')}}</b></span></div><div><i class="bi bi-whatsapp"></i><span>WhatsApp Support<b>Fastest response</b></span></div><div><i class="bi bi-calendar3"></i><span>Office Hours<b>{{value('contact_office_days','Monday–Friday')}}</b></span></div></div>
  </div></section>
  <section class="contact-faq"><div class="container"><div class="contact-heading text-center"><span>FAQ</span><h2>Before You Contact Us</h2></div><div class="accordion" id="contactFaq"><div v-for="(faq,index) in faqs" :key="faq[0]" class="accordion-item"><h3 class="accordion-header"><button class="accordion-button" :class="{collapsed:index!==0}" type="button" data-bs-toggle="collapse" :data-bs-target="`#faq-${index}`">{{faq[0]}}</button></h3><div :id="`faq-${index}`" class="accordion-collapse collapse" :class="{show:index===0}" data-bs-parent="#contactFaq"><div class="accordion-body">{{faq[1]}}</div></div></div></div></div></section>
  <section class="contact-final"><div class="container text-center"><h2>Still Need Help?</h2><p>Our admissions team is ready to guide you toward the right nursing program.</p><div><a :href="phoneLink(value('college_phone'))" class="btn btn-light">Call Us</a><a :href="whatsAppLink(whatsapp)" target="_blank" rel="noopener" class="btn btn-outline-light">Chat on WhatsApp</a></div></div></section>
 </main>
 <SiteFooter :site="data.site"/>
</template>
